name: foodchronicle
layout_spectrum: 0.15699052228592336
typography_spectrum: 0.4349244220647961
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6735853429418057
  lightness: 0.8388924088794738
  saturation: 0.23581570573151112
  rhythmicContrast: 0.8729517797473818
purpose: []
title: food and travel
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
