name: foodchronicle
layout_spectrum: 0.23689
typography_spectrum: 0.9238711043726653
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors: []
  brandStrength: 0.09302766877226532
  lightness: 0.8284119067247957
  saturation: 0.4137985995039344
  rhythmicContrast: 0.6382650539744645
purpose: []
title: food and travel
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
