name: foodchronicle
favicon: null
layout_spectrum: 0.23689
typography_spectrum: 0.9238711043726653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.09302766877226532
  lightness: 0.8284119067247957
  saturation: 0.4137985995039344
  rhythmicContrast: 0.6382650539744645
purpose: []
